# Generated by Django 5.0.6 on 2024-06-14 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_description', models.CharField(max_length=100, verbose_name='Área')),
            ],
            options={
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_description', models.CharField(max_length=45, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name_plural': 'Prioridades',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_description', models.CharField(default='Abierto', max_length=45, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_description', models.CharField(max_length=45, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('phone', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.area', verbose_name='Área')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=200, verbose_name='Asunto')),
                ('opening_date', models.DateField(auto_now_add=True, verbose_name='Fecha Apertura')),
                ('observation', models.TextField(max_length=255, verbose_name='Observación')),
                ('solution', models.TextField(max_length=255, verbose_name='Solución')),
                ('closing_date', models.DateField(null=True, verbose_name='Fecha cierre')),
                ('asigned_area', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_area', to='Helpdesk.area', verbose_name='Área asignada')),
                ('closure_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_tickets', to='Helpdesk.profile', verbose_name='Agente cierre')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.profile', verbose_name='Cliente')),
                ('opening_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opened_tickets', to='Helpdesk.profile', verbose_name='Agente apertura')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.priority', verbose_name='Prioridad')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.status', verbose_name='Estado')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
